//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.4
//     from Assets/InputSystem/InputActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @InputActions : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @InputActions()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""InputActions"",
    ""maps"": [
        {
            ""name"": ""Player"",
            ""id"": ""14c91da6-3aa6-4d77-bce6-ca0b0edbc462"",
            ""actions"": [
                {
                    ""name"": ""ReloadPressed"",
                    ""type"": ""Button"",
                    ""id"": ""96afdf60-cb56-4162-861c-5b3c7acde56e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ReloadReleased"",
                    ""type"": ""Button"",
                    ""id"": ""fbbf0775-ab84-4c89-9b23-700b67831f96"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""AimPressed"",
                    ""type"": ""Button"",
                    ""id"": ""df90fb9c-ddb2-48b3-8a93-50b99fbd9eea"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""AimReleased"",
                    ""type"": ""Button"",
                    ""id"": ""feb7cd12-f104-4335-bb37-d326d988d7b7"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Fire"",
                    ""type"": ""Button"",
                    ""id"": ""d48cb071-527d-44c3-8d0d-071fa604236e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""2536c8b3-81c5-4817-9c75-4427ca8e7a7a"",
                    ""path"": ""<Keyboard>/r"",
                    ""interactions"": ""Press"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ReloadPressed"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""55a0473e-bd27-4771-940e-d1e59a18f5d2"",
                    ""path"": ""<Keyboard>/r"",
                    ""interactions"": ""Press(behavior=1)"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ReloadReleased"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""24980406-33f7-4009-bb82-5ab4a831e1cd"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""AimPressed"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""73ec93a4-adba-411e-82e6-0eabc36d14d0"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""AimReleased"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""de3cc723-2c72-4c86-9ef4-ac961925c177"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Fire"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Player
        m_Player = asset.FindActionMap("Player", throwIfNotFound: true);
        m_Player_ReloadPressed = m_Player.FindAction("ReloadPressed", throwIfNotFound: true);
        m_Player_ReloadReleased = m_Player.FindAction("ReloadReleased", throwIfNotFound: true);
        m_Player_AimPressed = m_Player.FindAction("AimPressed", throwIfNotFound: true);
        m_Player_AimReleased = m_Player.FindAction("AimReleased", throwIfNotFound: true);
        m_Player_Fire = m_Player.FindAction("Fire", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Player
    private readonly InputActionMap m_Player;
    private IPlayerActions m_PlayerActionsCallbackInterface;
    private readonly InputAction m_Player_ReloadPressed;
    private readonly InputAction m_Player_ReloadReleased;
    private readonly InputAction m_Player_AimPressed;
    private readonly InputAction m_Player_AimReleased;
    private readonly InputAction m_Player_Fire;
    public struct PlayerActions
    {
        private @InputActions m_Wrapper;
        public PlayerActions(@InputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @ReloadPressed => m_Wrapper.m_Player_ReloadPressed;
        public InputAction @ReloadReleased => m_Wrapper.m_Player_ReloadReleased;
        public InputAction @AimPressed => m_Wrapper.m_Player_AimPressed;
        public InputAction @AimReleased => m_Wrapper.m_Player_AimReleased;
        public InputAction @Fire => m_Wrapper.m_Player_Fire;
        public InputActionMap Get() { return m_Wrapper.m_Player; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayerActions set) { return set.Get(); }
        public void SetCallbacks(IPlayerActions instance)
        {
            if (m_Wrapper.m_PlayerActionsCallbackInterface != null)
            {
                @ReloadPressed.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnReloadPressed;
                @ReloadPressed.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnReloadPressed;
                @ReloadPressed.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnReloadPressed;
                @ReloadReleased.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnReloadReleased;
                @ReloadReleased.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnReloadReleased;
                @ReloadReleased.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnReloadReleased;
                @AimPressed.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnAimPressed;
                @AimPressed.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnAimPressed;
                @AimPressed.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnAimPressed;
                @AimReleased.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnAimReleased;
                @AimReleased.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnAimReleased;
                @AimReleased.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnAimReleased;
                @Fire.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnFire;
                @Fire.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnFire;
                @Fire.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnFire;
            }
            m_Wrapper.m_PlayerActionsCallbackInterface = instance;
            if (instance != null)
            {
                @ReloadPressed.started += instance.OnReloadPressed;
                @ReloadPressed.performed += instance.OnReloadPressed;
                @ReloadPressed.canceled += instance.OnReloadPressed;
                @ReloadReleased.started += instance.OnReloadReleased;
                @ReloadReleased.performed += instance.OnReloadReleased;
                @ReloadReleased.canceled += instance.OnReloadReleased;
                @AimPressed.started += instance.OnAimPressed;
                @AimPressed.performed += instance.OnAimPressed;
                @AimPressed.canceled += instance.OnAimPressed;
                @AimReleased.started += instance.OnAimReleased;
                @AimReleased.performed += instance.OnAimReleased;
                @AimReleased.canceled += instance.OnAimReleased;
                @Fire.started += instance.OnFire;
                @Fire.performed += instance.OnFire;
                @Fire.canceled += instance.OnFire;
            }
        }
    }
    public PlayerActions @Player => new PlayerActions(this);
    public interface IPlayerActions
    {
        void OnReloadPressed(InputAction.CallbackContext context);
        void OnReloadReleased(InputAction.CallbackContext context);
        void OnAimPressed(InputAction.CallbackContext context);
        void OnAimReleased(InputAction.CallbackContext context);
        void OnFire(InputAction.CallbackContext context);
    }
}
